# Generated by Django 3.1.3 on 2021-01-19 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('meal_type', models.CharField(choices=[('v', 'Vegan'), ('n', 'Non-Vegan')], help_text='Select the type of meal', max_length=1)),
                ('meal_pic', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_meal', models.DateField()),
                ('day_of_week', models.CharField(choices=[('m', 'Monday'), ('t', 'Tuesday'), ('w', 'Wednesday'), ('th', 'Thursday'), ('f', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], help_text='Day of the Week', max_length=3)),
                ('cook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meals', to=settings.AUTH_USER_MODEL)),
                ('meal', models.ManyToManyField(help_text='Choose meal for the day', to='planner.Meal')),
            ],
            options={
                'ordering': ['date_meal'],
            },
        ),
    ]
