# Generated by Django 3.1.3 on 2020-12-30 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=500)),
                ('meal_type', models.CharField(choices=[('v', 'Vegan'), ('n', 'Non-Vegan')], help_text='Select the type of meal', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('m', 'Monday'), ('t', 'Tuesday'), ('w', 'Wednesday'), ('th', 'Thursday'), ('f', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], help_text='Day of the Week', max_length=3)),
                ('date_meal', models.DateField()),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.meal')),
            ],
            options={
                'ordering': ['date_meal'],
            },
        ),
    ]
