# Generated by Django 3.1.3 on 2021-01-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20210105_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='meal',
        ),
        migrations.AddField(
            model_name='day',
            name='meal',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='planner.Meal'),
        ),
    ]
