# Generated by Django 3.1.3 on 2021-01-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20210105_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='meal',
            field=models.ManyToManyField(help_text='Select a meal', to='planner.Meal'),
        ),
    ]
