# Generated by Django 3.1.3 on 2021-01-05 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0007_auto_20210105_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='cook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
