# Generated by Django 3.1.3 on 2021-01-05 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_meal_cook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='meal',
        ),
        migrations.AddField(
            model_name='day',
            name='meal',
            field=models.ForeignKey(help_text='Select a meal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal', to='planner.meal'),
        ),
    ]
