# Generated by Django 3.1.3 on 2021-01-05 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0009_auto_20210105_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='cook',
        ),
        migrations.AlterField(
            model_name='day',
            name='cook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='day',
            name='meal',
        ),
        migrations.AddField(
            model_name='day',
            name='meal',
            field=models.ManyToManyField(help_text='Select a meal', to='planner.Meal'),
        ),
    ]
