# Generated by Django 3.1.3 on 2021-01-06 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0011_auto_20210106_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='cook',
        ),
        migrations.AddField(
            model_name='day',
            name='cook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='day',
            name='meal',
        ),
        migrations.AddField(
            model_name='day',
            name='meal',
            field=models.ManyToManyField(help_text='Choose meal for the day', to='planner.Meal'),
        ),
    ]
