# Generated by Django 3.1.3 on 2021-01-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_auto_20210106_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='ingredients',
            field=models.TextField(),
        ),
    ]
