# Generated by Django 3.1.3 on 2021-01-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_auto_20210107_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['date_meal']},
        ),
    ]
